services:
    php:
        container_name: php
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 80:80
        volumes:
            - .:/var/www/html
            - vendor:/var/www/html/vendor
        depends_on:
            - db
        restart: always
        networks:
            - kanboard_network

    db:
        image: mariadb:latest
        container_name: mariadb
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: breaking_task
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        restart: always
        networks:
            - kanboard_network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        depends_on:
            - db
        restart: always
        networks:
            - kanboard_network

networks:
    kanboard_network:

volumes:
    vendor: